### ISSUE TITLE
XMLParser not compatible with Pharo 9

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-contributions/XML-XMLParser#2]
The XMLParser is not compatible with Pharo 9. It has Glamour image dependencies that raise errors during loading and uses removed old file streams.

**Comment by astares** [comment]
I guess this is due to package XML-Parser-GTExtensions which now needs a replacement for Spec2

**Comment by astares** [comment]
Also it looks like GT classes have been thrown out in Pharo 9 instead of correctly deprecating them. I understand that we want to get rid of them - but some rough compatibility to help in transitions should have been given otherwise we constantly break Pharo users packages.

![Uploading image.png…]()

**Comment by pavel-krivanek** [comment]
the GT compatibility is not the biggest issue: https://github.com/pharo-contributions/Athens-SVG/issues/9

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/117360629-500acd00-aeb9-11eb-943b-3d37d601c44d.png)

**Comment by bpieber** [comment]
In addition to the missing GLMHighlighterTextStylerDecorator there is also an issue because XMLParser package references StandardFileStream. Although the tests are all green XMLDOMParser>>#parseFileNamed: fails with an XMLFileException: File reading unspported.

I could not find anything on the mailing list about what to replace the removed StandardFileStream with. Is there some kind of migration guide for moving away from StandardFileStream?

**Comment by Robert-Briggs** [comment]
I am also having problems with the parser.  The samples in the ReadMe are not parsed into a proper set of nodes.
See attached screenshot on the inspector
<img width="957" alt="Screenshot 2022-01-06 at 13 38 22" src="https://user-images.githubusercontent.com/69461242/148391495-86fa94bc-5727-4827-921c-797e919e9d68.png">
The whole document is copied to a single item in the nodes collection.

**Comment by Robert-Briggs** [comment]
Belay my comment.  It's my misunderstanding of the way the information is processed.  However, on issue I have is lack of examples or user documentation.  I'm managing to get things working by a process of trial and error and investigating the cases and messages but it is somewhat counter-intuitive, and there may be easier ways to use it than I have discovered so far.

**Comment by Ducasse** [comment]
If you have examples and little comments please push them to the repo.

**Comment by Robert-Briggs** [comment]
> If you have examples and little comments please push them to the repo.

Thanks but I've decided to remove  the comments as I'm not sure they are appropriate.

**Comment by tinchodias** [comment]
Hi, I've loaded without any issue the project in Pharo 10.

First, I downloaded pharo with `curl https://get.pharo.org/100+vm | bash`.
Second, I evaluated the README code:
```
Metacello new
	baseline: 'XMLParser';
	repository: 'github://pharo-contributions/XML-XMLParser/src';
	load.
```
So I wonder:
Is this issue still valid?
